config/routes.rb
require 'sidekiq/web'

Snpr::Application.routes.draw do
  root :to => 'index#index' # change this, maybe

  resources :static
  resources :phenotypes do
    member do
      get :feed
      get :get_genotypes
    end
  end
  resources :picture_phenotypes do
    member do
      get :feed
    end
  end
  resources :user_picture_phenotypes
  resources :genotypes
  resources :user_phenotypes
  resources :snps
  resources :users
  resource :user_session
  resources :user_snps
  resources :password_resets
  resources :news
  resources :messages
  resources :snp_comments
  resources :phenotype_comments
  resources :picture_phenotype_comments
  resources :search_results
  resources :achievements
  resources :user_achievements
  resources :index

  post '/fitbit/notification/', :to => 'fitbit_profiles#new_notification'
  get '/fitbit/start_auth', :to => 'fitbit_profiles#start_auth'
  get '/fitbit/verify', :to => 'fitbit_profiles#verify_auth'
  get '/fitbit/info', :to => 'fitbit_profiles#info'
  get '/fitbit/edit', :to => 'fitbit_profiles#edit'
  get '/fitbit/init', :to => 'fitbit_profiles#init'
  post '/fitbit/update/', :to => 'fitbit_profiles#update'
  get '/fitbit/delete/', :to => 'fitbit_profiles#destroy'
  get '/fitbit/show/:id', :to => 'fitbit_profiles#show', :as => :fitbit_show
  get '/fitbit/dump/:id', :to => 'fitbit_profiles#dump', :as => :fitbit_dump
  get '/fitbit/', :to => 'fitbit_profiles#index', :as => :fitbit_index
  get '/phenotypesets/enter/:id', :to => "phenotype_sets#enter_userphenotypes"
  get '/phenotypesets/user_phenotypes/save', :to => "phenotype_sets#save_user_phenotypes"
  get '/users/:id/changepassword', :to => 'users#changepassword'
  get '/signup', :to => 'users#new', as: :signup
  get '/signin', :to => 'user_sessions#new', :as => :login
  get '/signout', :to => 'user_sessions#destroy', :as => :logout
  get '/faq', :to => 'static#faq'
  get '/disclaimer', :to => 'static#disclaimer'
  get '/statistics', :to => 'static#statistics'
  get '/user_index', :to => 'users#index'
  get '/rss', :to => 'genotypes#feed', :as => :feed, :defaults => {:format => 'rss' }
  get '/search', :to => 'search_results#search'
  get '/users/:id/remove_help_one', :to => 'users#remove_help_one'
  get '/users/:id/remove_help_two', :to => 'users#remove_help_two'
  get '/users/:id/remove_help_three', :to => 'users#remove_help_three'
  get '/phenotypes/get_genotypes/:phenotype_id/:variation', :to => 'phenotypes#get_genotypes'
  get 'get_dump', :to => 'genotypes#get_dump'
  get '/phenotypes/:id/rss', :to => 'phenotypes#feed', :defaults => { :format => 'rss' }
  get '/dump_download', :to => 'genotypes#dump_download'
  get '/snps/json/annotation/:snp_name', :to => 'snps#json_annotation'
  get '/snps/json/:snp_name/:user_id', :to => 'snps#json'
  get '/phenotypes/json/variations/:phenotype_id', :to => 'phenotypes#json_variation'
  get '/phenotypes/json/:user_id', :to => 'phenotypes#json'
  get '/das/:id/features', :to => 'das#show'
  get '/das/sources', :to => 'das#sources'
  get '/das/:id/', :to => 'das#startpoint'
  get '/paper/rss', :to => 'news#paper_rss', :defaults => { :format => 'rss' }
  get '/recommend_phenotype/:id/', :to => 'phenotypes#recommend_phenotype'
  get '/press', :to => 'static#press'
  get '/blog' => redirect("http://opensnp.wordpress.com")
  get '/user_picture_phenotypes/:id/edit', :to => 'user_picture_phenotypes#edit'
  get '/user_picture_phenotypes/:id/delete', :to => 'user_picture_phenotypes#delete'
  get '/beacon/rest/responses', :to => 'beacon#responses'

  mount Sidekiq::Web => '/sidekiq'
end

app/models/fitbit_profile.rb
class FitbitProfile < ActiveRecord::Base
  belongs_to :user
  has_many :fitbit_bodies, dependent: :destroy
  has_many :fitbit_activities, dependent: :destroy
  has_many :fitbit_sleeps, dependent: :destroy
end

app/controllers/fitbit_profiles_controller.rb
class FitbitProfilesController < ApplicationController
  before_filter :require_user, except: [:new_notification, :show, :index]
  before_filter :require_user, only: [:update,:destroy,:init,:edit,:start_auth,:verify_auth,:dump]
  protect_from_forgery :except => :new_notification 
  helper_method :sort_column, :sort_direction

  def index
    @title = "Listing all connected Fitbit accounts"
    @fitbit_profiles = FitbitProfile
      .includes(:user)
      .order("#{sort_column} #{sort_direction}")
      .paginate(page: params[:page], per_page: 20)
  end
  
  def show
    @fitbit_profile = FitbitProfile.find_by_id(params[:id]) || not_found
    @title = "Fitbit profile"
    
    #grab activity measures for graphs
    if @fitbit_profile.activities
      @activity = FitbitActivity
        .where(fitbit_profile_id: @fitbit_profile.id)
        .order(:date_logged)
      @total_length = 0 # sum of all steps which are not 0 and not nil

      @total_floors = []
      @total_steps = []
      @floors = []
      @steps = []
      @floor_counter = 0
      @step_counter = 0

      @activity.each do |a|
        # Sometimes, floors is nil and not a number - API problem?
        # Dismiss these entries
        if a.steps.nil? or a.floors.nil?
          next
        end

        if a.steps != 0
          @total_length += 1
        end

        @total_floors << [a.date_logged, @floor_counter += a.floors]
        @floors << [a.date_logged, a.floors]
        @steps << [a.date_logged, a.steps]
        @total_steps << [a.date_logged, @step_counter += a.steps]
      end

      if not @total_steps.empty?
        begin
          @mean_steps = @total_steps[-1][-1] / @total_length #@activity.length
        rescue
        end
      end
    end
    
    #grab body measurements for graphs
    if @fitbit_profile.body
      @body = FitbitBody
        .where(fitbit_profile_id: @fitbit_profile.id)
        .order(:date_logged)
      @bmi = @body.map {|fa| [fa.date_logged, fa.bmi]}
    end
    
    #grab sleep measurements for graphs
    if @fitbit_profile.sleep
      @sleep = FitbitSleep
        .where(fitbit_profile_id: @fitbit_profile.id)
        .order(:date_logged)

      @total_minutes_asleep = []
      @total_minutes_to_sleep = []
      @minutes_asleep = []
      @minutes_to_sleep = []
      @awakenings = []
      @total_to_sleep_counter = 0
      @total_asleep_counter = 0
      @no_sleep = 0

      @sleep.each do |s|
        # Here again, some have nils
        # Skip these
        if s.minutes_to_sleep.nil? or s.minutes_asleep.nil?
          next
        end

        if s.minutes_asleep == 0
          @no_sleep += 1
        end

        @total_minutes_to_sleep << [s.date_logged, @total_to_sleep_counter += s.minutes_to_sleep]
        @total_minutes_asleep << [s.date_logged, @total_asleep_counter += s.minutes_asleep]
        @minutes_asleep << [s.date_logged, s.minutes_asleep]
        @minutes_to_sleep << [s.date_logged, s.minutes_to_sleep]
        @awakenings << [s.date_logged, s.number_awakenings]
      end

      if not @total_minutes_asleep.empty?
        begin
          @mean_sleep = @total_minutes_asleep[-1][-1] / (@sleep.length - @no_sleep)
        rescue
        end
      end
    end
  end
  
  def dump
    @fitbit_profile = FitbitProfile.find_by_id(params[:id]) || not_found
    Sidekiq::Client.enqueue(FitbitDump,current_user.email,@fitbit_profile.id)
    respond_to do |format|
      format.html
    end
  end
  
  def info
    respond_to do |format|
      format.html
    end
  end
    
  def edit
    @fitbit_profile = current_user.fitbit_profile
    respond_to do |format|
      format.html
    end
  end
  
  def destroy
    @fitbit_profile = current_user.fitbit_profile
    Sidekiq::Client.enqueue(FitbitEndSubscription,@fitbit_profile.id)
    respond_to do |format|
      format.html
    end
  end

  def init
    @user = current_user
    @fitbit_profile = @user.fitbit_profile
    
    respond_to do |format|
      format.html
    end
  end
  
  def update
    @fitbit_profile = FitbitProfile.find_by_id(params[:fitbit_profile][:id])
    @fitbit_profile.body = params[:fitbit_profile]["body"]
    @fitbit_profile.activities = params[:fitbit_profile]["activities"]
    @fitbit_profile.sleep = params[:fitbit_profile]["sleep"]
    @fitbit_profile.save
    Sidekiq::Client.enqueue(FitbitEdit,@fitbit_profile.id)
    redirect_to "/fitbit/edit"
  end

  def start_auth
    @user = current_user
    if @user.fitbit_profile == nil
      @user.fitbit_profile = FitbitProfile.new
      @user.save
    end
    print @user
    @fitbit_profile = @user.fitbit_profile 
    print @fitbit_profile
    client = Fitgem::Client.new(consumer_key: ENV.fetch('FITBIT_CONSUMER_KEY'),
                                consumer_secret: ENV.fetch('FITBIT_CONSUMER_SECRET'))
    request_token = client.request_token
    @fitbit_profile.request_token = request_token.token
    @fitbit_profile.request_secret = request_token.secret
    @fitbit_profile.save
    redirect_to "http://www.fitbit.com/oauth/authorize?oauth_token=#{request_token.token}"
  end
  
  def verify_auth
    @user = current_user
    @fitbit_profile = @user.fitbit_profile
    if params[:oauth_token] && params[:oauth_verifier]
      @client = Fitgem::Client.new(consumer_key: ENV.fetch('FITBIT_CONSUMER_KEY'),
                                   consumer_secret: ENV.fetch('FITBIT_CONSUMER_SECRET'))
      token = params[:oauth_token]
      secret = @fitbit_profile.request_secret
      verifier = params[:oauth_verifier]
      begin 
        access_token = @client.authorize(token, secret, { :oauth_verifier => verifier })
      rescue
        flash[:warning] = "Something went wrong while authenticating your FitBit-Account. Please try again."
        redirect_to :action => "info"
      end
      @fitbit_profile.access_token = access_token.token
      @fitbit_profile.access_secret = access_token.secret
      @fitbit_profile.verifier = verifier
      @fitbit_profile.save
      Sidekiq::Client.enqueue(FitbitInit,@fitbit_profile.id)
      flash[:notice] = "Successful login with FitBit!"
      redirect_to :action => "init"
    else
      flash[:warning] = "Something went wrong while authenticating your FitBit-Account. Please try again."
      redirect_to :action => "info"
    end
  end
  
  def new_notification
    puts params
    @json_object = params["updates"]
    @json_unparsed = @json_object.read
    @notification = JSON.parse(@json_unparsed)
    puts @notification[0]
    puts @notification[0]["collectionType"]
    Sidekiq::Client.enqueue(FitbitNotification,@notification)
    render :nothing => true, :status => 204
  end

  private

  def require_owner
    unless current_user == FitbitProfile.find(params[:fitbit_profile][:id]).user.id
      store_location
      if current_user
        return true
      else
        flash[:notice] = "You need to be logged in"
        redirect_to "/signin"
      end
      return false
    end
  end
  
  def sort_column
    Genotype.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
  end

  def sort_direction
    %w[desc asc].include?(params[:direction]) ? params[:direction] : "desc"
  end

end

app/views/fitbit_profiles/_form.html.erb
<h1><em>Fitbit</em> Settings</h1>

<div class="row">
  <div class="span6">
<%= form_for @fitbit_profile, :url => fitbit_update_path, :method => :post, :html => {:class => "form-horizontal"} do |f|%>
<h5> For which categories should we save data?</h5>
  <%= f.error_messages %>
  <%= f.check_box :body %> Body (Weight and Body Mass Index)<br />
  <%= f.check_box :activities %> Activities (Steps taken and Floors climbed)<br />
  <%= f.check_box :sleep %> Sleep (Duration, times awoken, time until asleep, length of wake-phases)<br />
  <%= f.hidden_field :id, :value => @fitbit_profile.id %>
<br />
<div class="alert alert-info">
  If you decide to uncheck some of the categories all data that has been saved so far will get deleted.
</div>
  <%= f.submit "Save Fitbit-Settings", {:class=>"btn btn-info"}%>
<% end %>

<div class="alert alert-warning">
  If you remove your <em>Fitbit</em>-account we will stop to grab new data and remove all the data that was already saved.
</div> 

<%=link_to("Remove Fitbit-account",{:controller => "fitbit_profiles", :action => "destroy"},:class => "btn btn-danger")%>

  </div>
  <div class="span6">
    <p>We will save data from three different categories: <strong>Body</strong>, <strong>Activities</strong> and <strong>Sleep</strong>.</p>
    <p>For the <strong>Body</strong> category we will save your Body Mass Index (BMI) and your weight (Unfortunately there's currently no option to get your height through <em>Fitbit</em> but you can calculate it through BMI and weight).</p>
    <p>For <strong>Sleep</strong> we will save how long you have slept and how often you have awoke, how long you've been awake and how long it took you to fall asleep.</p>
      <p>For the <strong>Activities</strong> we will save how many steps you have taken and how many floors you have climbed.</p><p>We will try to save the data you have uploaded to <em>Fitbit</em> up to now as well. You can decide which categories we should save. So if you feel comfortable to share your activities but neither weight nor sleep information that's no problem.</p>
    

  </div>
</div>

app/views/fitbit_profiles/destroy.html.erb
<legend>Deleted your <em>Fitbit</em>-connection</legend>

<p class="lead">Your <em>Fitbit</em>-account has been unlinked from openSNP. All <em>Fitbit</em>-data which we had saved has been deleted and we will not get any more updates, as long as you don't <%=link_to("reconnect your Fitbit account with openSNP",{:controller => "fitbit_profiles", :action => "start_auth"})%>.</p>

app/views/fitbit_profiles/dump.html.erb
<legend><%=image_tag("fitbit-icon.png")%> Dumping <em>Fitbit</em> data for <%=@fitbit_profile.user.name%></legend>
<p class="lead">You have requested <em>Fitbit</em> data for the user <%= link_to(@fitbit_profile.user.name, @fitbit_profile.user)%>. The data is currently prepared and you will receive an email as soon as the data is ready to be downloaded. <%=link_to("Return to the Fitbit Profile" ,{:controller => "fitbit_profiles", :action => "show", :id => @fitbit_profile.id})%>.</p>

app/views/fitbit_profiles/edit.html.erb
<%=render "form"%>

app/views/fitbit_profiles/index.html.erb
<legend><%=image_tag("fitbit-icon.png")%> Listing all connected <em><%=link_to("Fitbit",{:controller => "fitbit_profiles",:action => "info"},:rel => "tooltip", :title => "Want to learn more about our Fitbit-integration? Click here")%></em> accounts </legend>

<h4>
  <%= link_to(Zipfulldata.public_path, title: "Request download") do %>
    <%= image_tag("filedownload_small.png", style: "vertical-align:middle") %>
    Download the dump: Includes all genotyping files plus a CSV with all phenotypes of those users <%= Zipfulldata.gb_size %>
<% end %>
</h4>
<br/>
<h4><a href="https://github.com/superbobry/snpy">Python-library to parse the provided files</a>, courtesy of <a href="https://github.com/superbobry/">Sergei Lebedev</a></h4>
<br/>
<table class="table table-striped" id="all_fitbit">
  <tr>
    <th>#</th>
    <th><%= sortable "fitbit_user_id", "Fitbit ID"%></th>
    <th>User</th>
    <th><%= sortable "activities", "Shares Activities"%></th>
    <th><%= sortable "body", "Shares Body Data"%></th>
    <th><%= sortable "sleep", "Shares Sleep Data"%></th>
    <th>View Profile</th>
  </tr>
  <% @fitbit_profiles.each_with_index do |fitbit_profile, i| %>
    <tr>
      <td><%= table_row_sequence_number(@fitbit_profiles, i) %></td>
      <td><%= link_to(fitbit_profile.fitbit_user_id, {:controller => "fitbit_profiles", :action => "show", :id => fitbit_profile.id}) %></td>
      <td><%=image_tag fitbit_profile.user.avatar.url(:head),:style => "vertical-align:middle"%><%= link_to(fitbit_profile.user.name, fitbit_profile.user)%></td>
      <td><%if fitbit_profile.activities == true%><i class="icon-ok"></i><%else%><i class="icon-remove"></i><%end%></td>
      <td><%if fitbit_profile.body == true%><i class="icon-ok"></i><%else%><i class="icon-remove"></i><%end%></td>
      <td><%if fitbit_profile.sleep == true%><i class="icon-ok"></i><%else%><i class="icon-remove"></i><%end%></td>
      <td><%= link_to("view", {:controller => "fitbit_profiles", :action => "show", :id => fitbit_profile.id})%></td>
    </tr>
  <% end %>
</table>

<%= page_navigation_links @fitbit_profiles %>

<script type="text/javascript">
  $(document).ready(function () {
    $("[rel=tooltip]").tooltip({placement:'left'});
  });
</script>

app/views/fitbit_profiles/info.html.erb
<legend>Connect your <%=image_tag("fitbit_logo_dark_100px.png")%>  account to openSNP</legend>
<p class="lead"><em><a href="http://www.fitbit.com">Fitbit</a></em> is a wearable gadget which allows you to track your activities (How many steps have you taken? How many floors have you climbed?), your sleep (How long did you sleep? How often have you awoken at night?) and also allows you to track your body-development (i.e. your weight/BMI). The data collected by and through your <em>Fitbit</em> is a valuable extension of the phenotypes you've already entered in openSNP.</p>

<p class="lead">Once you've connected your <em>Fitbit</em> account to openSNP we will automatically get your latest data from FitBit. Each time you synchronize your <em>Fitbit</em>-tracker or enter new data on <em>Fitbit</em> the changes will also appear on openSNP. Currently we save data about your activities, your body and your sleep.</p>

<p class="lead">The data will be public on the openSNP-website, like all other phenotypes. However, you can decide which categories you will connect with openSNP and which not.</p>

<%if current_user != nil%>
<h4><%=link_to("Connect your Fitbit account with openSNP",{:controller => "fitbit_profiles", :action => "start_auth"},:class => "btn btn-info")%></h4>
<%else%>
<p class="lead"><%=link_to("Sign in", '/signin')%> to openSNP to connect your <em>Fitbit</em> account with us.</p>
<%end%>
You want to learn more about the integration of Fitbit into openSNP or have a question? <%=link_to("Have a look at the FAQ.","/faq#enteringphenotypes")%>

app/views/fitbit_profiles/init.html.erb
<p class="lead">Your <em>Fitbit</em>-account has been connected to your openSNP-account. <strong>Please finish the initial setup below so we can start to save your <em>Fitbit</em>-results</strong>.</p>

<%=render "form"%>

app/views/fitbit_profiles/show.html.erb
<legend><%=image_tag("fitbit-icon.png",:style => "vertical-align:middle")%> <em><%=link_to("Fitbit",{:controller => "fitbit_profiles",:action => "info"},:rel => "tooltip", :title => "Want to learn more about our Fitbit-integration? Click here")%></em> profile for <%= link_to(@fitbit_profile.user.name, @fitbit_profile.user)%></legend>
<%if current_user%>
<p class="lead"><%=link_to(image_tag("filedownload_small.png",:style => "vertical-align:middle"),{:controller => "fitbit_profiles", :action => "dump", :id => @fitbit_profile.id})%> <%=link_to("Download a dump of the data",{:controller => "fitbit_profiles", :action => "dump", :id => @fitbit_profile.id})%></p>
<%else%>
<p class="lead">If you log in to <em>openSNP</em> you can download a CSV-file with all the data.</p>
<%end%>

<%if @activity != nil%>
  <legend>Activity Measurements</legend>
  <script type="text/javascript">
  $(document).ready(function(){
    // Activity Graph
    var steps=<%=raw(@steps.to_json)%>;
    var floors=<%=raw(@floors.to_json)%>;
    var plot1 = $.jqplot('chart1', [floors,steps], {
        title:'Activity per Day (Mean steps/day: <%=@mean_steps%>)',
        series:[{label:'Floors' ,yaxis:'y2axis',fill: true,fillAlpha: 0.8,highlightMouseOver: false}, {label:'Steps'}],
        axes:{
          xaxis:{
            renderer:$.jqplot.DateAxisRenderer,
            tickOptions:{
              formatString:'%b&nbsp;%#d'
            } 
          },
          yaxis:{
            tickOptions:{
              formatString:'%i steps'
              }
          },
          y2axis:{
            tickOptions:{
              formatString:'%i floors'
            },
          },
        },
        axesDefaults: {
            pad: 0
        },
        legend: {
                    show: true,
                    placement: 'outsideGrid'
                },
        highlighter: {
          show: true,
          sizeAdjust: 7.5
        },
        cursor: {
          show: false
        }
    });
    // Sum Activity Graph
    var total_steps=<%=raw(@total_steps.to_json)%>;
    var total_floors=<%=raw(@total_floors.to_json)%>;
    var plot2 = $.jqplot('chart2', [total_floors,total_steps], {
        title:'Sum of Activity',
        series:[{label:"Floors",yaxis:'y2axis',fill:true,fillAlpha:0.5},{label:'Steps',fill:true,fillAlpha:0.5}],
        axes:{
          xaxis:{
            renderer:$.jqplot.DateAxisRenderer,
            tickOptions:{
              formatString:'%b&nbsp;%#d'
            } 
          },
          yaxis:{
            tickOptions:{
              formatString:'%i steps'
              }
          },
          y2axis:{
            tickOptions:{
              formatString:'%i floors'
            },
          },
        },
        axesDefaults: {
            pad: 0
        },
        legend: {
                    show: true,
                    placement: 'outsideGrid'
                },
        highlighter: {
          show: true,
          sizeAdjust: 7.5
        },
        cursor: {
          show: false
        }
    });
  });
  </script>
  <div id="chart1"></div>
  <div id="chart2"></div>
<%end%>

<%if @body and @body != [] %>
  <legend>Body Measurements</legend>
  <script type="text/javascript">
  $(document).ready(function(){
    // BMI Graph
    var bmi=<%=raw(@bmi.to_json)%>;
    var plot3 = $.jqplot('chart3', [bmi], {
        title:'BMI per Day',
        series:[{label:'Body Mass Index',fill:true}],
        axes:{
          xaxis:{
            renderer:$.jqplot.DateAxisRenderer,
            tickOptions:{
              formatString:'%b&nbsp;%#d'
            } 
          },
          yaxis:{
            tickOptions:{
              formatString:'%.2f BMI'
              }
          },
        },
        axesDefaults: {
        },
        legend: {
                    show: true,
                    placement: 'outsideGrid'
                },
        highlighter: {
          show: true,
          sizeAdjust: 7.5
        },
        cursor: {
          show: false
        }
    });
  });
  </script>
  <div id="chart3"></div>
<%end%>

<%if @sleep and  @sleep != [] %>
  <legend>Sleep Measurements</legend>
  <script type="text/javascript">
  $(document).ready(function(){
    // Activity Graph
    var minutes_asleep=<%=raw(@minutes_asleep.to_json)%>;
    var minutes_to_sleep=<%=raw(@minutes_to_sleep.to_json)%>;
    var awakenings=<%=raw(@awakenings.to_json)%>;
    var plot4 = $.jqplot('chart4', [awakenings,minutes_asleep,minutes_to_sleep], {
        title:'Sleep per Day (Mean sleep/day: <%=@mean_sleep%> minutes)',
        series:[{label:'# awaken' ,yaxis:'y2axis',fill: true,highlightMouseOver: false}, {label:'Minutes asleep'},{label: 'Minutes awake',fill:true}],
        axes:{
          xaxis:{
            renderer:$.jqplot.DateAxisRenderer,
            tickOptions:{
              formatString:'%b&nbsp;%#d'
            } 
          },
          yaxis:{
            tickOptions:{
              formatString:'%i minutes'
              }
          },
          y2axis:{
            tickOptions:{
              formatString:'%i times awoken'
            },
          },
        },
        axesDefaults: {
            pad: 0
        },
        legend: {
                    show: true,
                    placement: 'outsideGrid'
                },
        highlighter: {
          show: true,
          sizeAdjust: 7.5
        },
        cursor: {
          show: false
        }
    });
    // Sum Activity Graph
    var total_minutes_asleep=<%=raw(@total_minutes_asleep.to_json)%>;
    var total_minutes_to_sleep=<%=raw(@total_minutes_to_sleep.to_json)%>;
    var plot5 = $.jqplot('chart5', [total_minutes_asleep,total_minutes_to_sleep], {
        title:'Sum of Sleep',
        series:[{label:'minutes asleep',fill:true,fillAlpha:0.5},{label:"minutes falling asleep",yaxis:'y2axis',fill:true,fillAlpha:0.6}],
        axes:{
          xaxis:{
            renderer:$.jqplot.DateAxisRenderer,
            tickOptions:{
              formatString:'%b&nbsp;%#d'
            } 
          },
          yaxis:{
            tickOptions:{
              formatString:'%i min (asleep)'
              }
          },
          y2axis:{
            tickOptions:{
              formatString:'%i min (falling asleep)'
            },
          },
        },
        axesDefaults: {
            pad: 0
        },
        legend: {
                    show: true,
                    placement: 'outsideGrid'
                },
        highlighter: {
          show: true,
          sizeAdjust: 7.5
        },
        cursor: {
          show: false
        }
    });
  });
  </script>
  <div id="chart4"></div>
  <div id="chart5"></div>
<%end%>
<script type="text/javascript">
  $(document).ready(function () {
    $("[rel=tooltip]").tooltip({placement:'right'});
  });
</script>